name: Keep `.txt.wc` files up to date.

on:
  pull_request:
    branches:
      - 'main'

jobs:
  keep_wc_up_to_date:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Run
        run: ./.internal/wc_check.sh
